### ISSUE TITLE
Missing svglatex  file

### ISSUE THREAD

**Issue by TMRengarasu** [johnyf/svglatex#1]
Hi 
I am trying use your tools to create Beamer slides.

In the inkscape2tex.py  line 21 

`from svglatex import convert`
 I don't seem have the module can you point to this module place
Terrance

**Comment by johnyf** [comment]
Indeed, recent versions of the script `inkscape2tex.py` depend on a yet unreleased module, which is based on https://github.com/johnbartholomew/svg2latex/blob/master/svg2latex.py. Before sharing it, I need to contact the author of that script, because license information is not mentioned in that repository.

Meanwhile, what you can do is to use `inkscape`, by renaming a function call to `convert_svg_using_inkscape`, essentially rolling back the recent change fb937b2b9273e0a23d239fe9fa64384de1e1f957.

The reason for using a module, instead of directly the LaTeX export option of `inkscape` is because the latter is broken in `inkscape >= 0.91` in several ways:

- [latex linebreak error due to change to one box](https://bugs.launchpad.net/inkscape/+bug/1547357)
- [PDF+Latex export creates multipage pdf, pages missing](https://bugs.launchpad.net/ubuntu/+source/inkscape/+bug/1417470) (see also [this comment](http://stackoverflow.com/a/32112630/1959808))

(0.48.5 r10040 (Jul 12 2014) worked fine)

 So, the module `convert` extracts text from the SVG (thus replicating what `inkscape` was supposed to be doing properly), and then calls `inkscape` for exporting the graphics only (text has been removed by this point).

**Comment by TMRengarasu** [comment]
[in thi page](https://github.com/johnbartholomew/svg2latex) the author mentions license to be BSD 3-Clause License. 

Yea I have come across Inkscape  error also.
 Meanwhile i will try your suggestions.

**Comment by johnyf** [comment]
Yes, I contacted @johnbartholomew after posting the comment [above](https://github.com/johnyf/inkscape/issues/1#issuecomment-290514835) and his response was very timely (thank you very much @johnbartholomew). I added the modified module `svg2latex` and adjusted the import as of 27223e959727e9b0d549cf11978ea0fa97fe2fc7.

This should work for now. If @TMRengarasu you plan to use the scripts from another directory, then the import won't work, because `svg2latex` is not installed as a package. I plan to eventually release the code with a different structure (which won't have this issue), so I will let it be so here for now.

**Comment by johnyf** [comment]
@TMRengarasu has the OP been answered? Can we close the issue?

**Comment by TMRengarasu** [comment]
I am still getting  in valid argument raised from `svg2latex`  line 325. But I think that is a different new issue. This can be closed.

**Comment by johnyf** [comment]
`svg2latex` is not yet complete, so there may be several errors, depending on the SVG files used.
