### ISSUE TITLE
Document "no flowRect"

### ISSUE THREAD

**Issue by moy** [johnyf/svglatex#2]
Hi,

I just discovered inkscape2scenes.py which sounds great, but unfortunately I didn't manage to get it to work yet. I managed to create a layer labeled as "content", and I created a textfield from inkscape, but the script still complains with "Make sure you have a text box (with no flowRect)". Unfortunately, I couldn't find what "flowRect" is supposed to mean, and all google searches I did lead to this script or some of its variants.

Can you explain what a text box with no flowRect is, and how to obtain it?

Thanks,

**Comment by johnyf** [comment]
The message shown originates from [L130](https://github.com/johnyf/inkscape/blob/dev/inkscape2scenes.py#L130) which doesn't find a [suitable text element](https://github.com/johnyf/inkscape/blob/dev/inkscape2scenes.py#L128) in the SVG file. The `content` layer indeed [has been found](https://github.com/johnyf/inkscape/blob/dev/inkscape2scenes.py#L102) by that point.

@moy is the text box that you create within the layer named `content`? In Inkscape you can switch the layer being edited via Layer -> Layers. In Inkscape 0.92.1 r15371, I created an SVG with empty Layer 1 and a text box containing `background, layer1`. The reported error did not arise (due to the empty Layer 1 another error arose from `CairoRenderer`, but that is expected). Flowing/unflowing (Text -> Unflow), which I think is relevant, does not have any effect on the lone text box within the `content` layer.

A simple way to see whether the text box is there is to create a minimal SVG and open it in a text editor (Inkscape allows you to see the elements too, I believe from Object -> Objects) and look for a text box with the right text in the `content` layer. For example:

```svg
<g
     inkscape:groupmode="layer"
     id="layer2"
     inkscape:label="content">
    <text
       xml:space="preserve"
       style="font-style:normal;font-weight:normal;font-size:1.984375px;line-height:125%;font-family:sans-serif;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:0.26458332px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"
       x="48.242149"
       y="55.388344"
       id="text4519"><tspan
         sodipodi:role="line"
         id="tspan4517"
         x="48.242149"
         y="55.388344"
         style="stroke-width:0.26458332px"> background, layer1</tspan></text>
  </g>
```

It has been years since I last used the `inkscape2scenes.py` script, but I do not expect there to be any reasons why something would have changed (except for Inkscape bugs, which motivated changes to `inkscape2tex.py` recently).

**Comment by johnyf** [comment]
@moy was the issue resolved? I should also note that the notes about "flowRect" originate in `inkscapeslide` (https://github.com/abourget/inkscapeslide/blob/7509836ebe21abf53704138cad88266de65a9b57/inkscapeslide/__init__.py#L33). I do not recall having any issue related to this property.

**Comment by moy** [comment]
OK, I got it. There are two ways to create a textbox in inkscape, both involving the same tool (the **A** icon on the left sidebar):

* Drag the mouse to draw a rectangle, and type text inside. This is what `inkscape2scene.py` doesn't like, it produces a `flowRoot` instead:

```xml
    <flowRoot
       xml:space="preserve"
       id="flowRoot3337"
       style="font-style:normal;font-weight:normal;font-size:40px;line-height:125%;font-family:Sans;letter-spacing:0px;word-spacing:0px;fill:#000000;fill-opacity:1;stroke:none;stroke-width:1px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"><flowRegion
         id="flowRegion3339"><rect
           id="rect3341"
           width="562.85712"
           height="177.14287"
           x="54.285713"
           y="89.505058" /></flowRegion><flowPara
         id="flowPara3343">background, layer1</flowPara></flowRoot>  </g>
</svg>
```
* Just click (not drag), and type text. Then inkscape produces a `text` element which `inkscape2scene.py` accepts.

I think a hint (click, not drag) in the error message would greatly help.

> It has been years since I last used the inkscape2scenes.py script

Is it because you migrated to something else, or just because you don't need it at the moment?

**Comment by johnyf** [comment]
@moy, thanks for resolving this issue. I documented the findings in 0430dd8f53deaf0192f78a8bc832601afdd3b7cb.
Motivated by the XML code that you [reported](https://github.com/johnyf/inkscape/issues/2#issuecomment-298168351), I searched with [`ack flowRect`](https://github.com/petdance/ack2) within [the repository of `inkscape` @54100106e2ed](https://github.com/inkscape/inkscape/tree/54100106e2ed3890d9397c559cd75e52901121ba) and it turns out that `flowRect` is a name used by `inkscape`, much like `flowRoot`:

```
share/attributes/genMapDataCSS.pl
19:# Note "flowRoot, flowPara, flowSpan, flowRegion, and flowRect are Inkscape

share/attributes/genMapDataSVG.pl
81:push @{$attributes{ "class" }->{elements}}, "flowRoot","flowPara","flowSpan","flowRect","flowRegion","solidColor";
82:push @{$attributes{ "id"    }->{elements}}, "flowRoot","flowPara","flowSpan","flowRect","flowRegion","solidColor";
83:push @{$attributes{ "style" }->{elements}}, "flowRoot","flowPara","flowSpan","flowRect","flowRegion","solidColor";

share/attributes/svgprops
37:"class" - "a","altGlyph","circle","clipPath","defs","desc","ellipse","feBlend","feColorMatrix","feComponentTransfer","feComposite","feConvolveMatrix","feDiffuseLighting","feDisplacementMap","feFlood","feGaussianBlur","feImage","feMerge","feMorphology","feOffset","feSpecularLighting","feTile","feTurbulence","filter","font","foreignObject","g","glyph","glyphRef","image","line","linearGradient","marker","mask","missing-glyph","path","pattern","polygon","polyline","radialGradient","rect","stop","svg","switch","symbol","text","textPath","title","tref","tspan","use","flowRoot","flowPara","flowSpan","flowRect","flowRegion","solidColor"
129:"id" - "a","altGlyph","altGlyphDef","altGlyphItem","animate","animateColor","animateMotion","animateTransform","circle","clipPath","color-profile","cursor","defs","desc","ellipse","feBlend","feColorMatrix","feComponentTransfer","feComposite","feConvolveMatrix","feDiffuseLighting","feDisplacementMap","feDistantLight","feFlood","feFuncA","feFuncB","feFuncG","feFuncR","feGaussianBlur","feImage","feMerge","feMergeNode","feMorphology","feOffset","fePointLight","feSpecularLighting","feSpotLight","feTile","feTurbulence","filter","font","font-face","font-face-format","font-face-name","font-face-src","font-face-uri","foreignObject","g","glyph","glyphRef","hkern","image","line","linearGradient","marker","mask","metadata","missing-glyph","mpath","path","pattern","polygon","polyline","radialGradient","rect","script","set","stop","style","svg","switch","symbol","text","textPath","title","tref","tspan","use","view","vkern","flowRoot","flowPara","flowSpan","flowRect","flowRegion","solidColor","meshgradient","mesh","meshrow","meshpatch","hatch","hatchpath"
333:"style" - "a","altGlyph","circle","clipPath","defs","desc","ellipse","feBlend","feColorMatrix","feComponentTransfer","feComposite","feConvolveMatrix","feDiffuseLighting","feDisplacementMap","feFlood","feGaussianBlur","feImage","feMerge","feMorphology","feOffset","feSpecularLighting","feTile","feTurbulence","filter","font","foreignObject","g","glyph","glyphRef","image","line","linearGradient","marker","mask","missing-glyph","path","pattern","polygon","polyline","radialGradient","rect","stop","svg","switch","symbol","text","textPath","title","tref","tspan","use","flowRoot","flowPara","flowSpan","flowRect","flowRegion","solidColor"
```

This answers also the question of what a `flowRect` means.

Regarding my current practices, I still use `beamer`, but I usually prepare presentations with figures that are visible at once (not progressively using layers), so I don't use `inkscape2scenes.py`. The motivation has been mainly:

1. preparing layered figures can be time consuming (in the rare cases that I needed to split a figure into two stages or so I just copied it, because there wasn't much time available)
2. layered figures can slow down a presentation, and not as easy to accelerate when limited time remains to complete a presentation.
3. too step-by-step presentations are more appropriate for tutorials and one-hour talks, not so much for shorter presentations.

Of course, l still believe that layered figures are very appropriate for tutorials and presentations that are not subject to a hard time constraint.

I use the script `inkscape2tex.py` for all the graphics in any documents I write.
